language: scala
scala:
  - 2.11.7
  - 2.10.5
jdk:
  - oraclejdk7
  - openjdk7
sudo: false
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - bash <(curl -s https://codecov.io/bash)
